# image will be published to ghcr.io/<user>/<name>
name: my-bazzite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  # Install cli packages
  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - helix
      - fastfetch
      - eza
      - gh
      - ripgrep
      - zoxide
      - tealdeer
      - squashfs-tools # For working with systemd-sysext

  - type: script
    scripts:
      # - example.sh # Make it so GNOME Shell doesn't use Nvidia by default
      - tribuffer.sh # Replace VRR mutter with triple buffer mutter

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
